### ISSUE TITLE
Definição da engine

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/Main#12]
### Descrição:
Definir como podemos de melhor maneira definir como vamos desenvolver o projeto, existem dois caminhos, desenvolver uma engine ou utilizar de algumas já existentes

### Critérios de Aceitação
Critérios de aceitação para a Issue ser aceita.
- [ ] Solução para o desenvolvimento do projeto

### Tarefas
Seção para tarefas de Issues mais complexas. As tarefas devem garantir o perfeito funcionamento da Issue.
- [ ] Pesquisar dificuldade do desenvolvimento de engine
- [ ] Pesquisar por engine já existentes em Python
- [ ] Reunião do time para tomada de decisão

**Comment by arthurbdiniz** [comment]
@Desenho2018-2/main alguém já chegou a pesquisar sobre algum motor gráfico? Eu olhei sobre a PyGame e conversei com o professor Fabio hoje, ele disse que a PyGame está bastante descontinuada e que seria interessante a gente pesquisar por engines que ainda estão sendo atualizadas

**Comment by vitorfhc** [comment]
Então, depois de algumas pesquisas eu acredito que Python não seja a melhor solução mesmo que o time tenha maior proeficiência nele. O que nós precisamos é de renderização básica que não nos dê nenhum overhead e maneiras eficientes e simples de pegar inputs, assim não perdemos tempo com coisas de nível baixo e que não irão agregar valor ao objetivo da matéria.

Minha sugestão é sair do Python para o Javascript que já tem suporte para ambos nativamente, tanto renderização quanto inputs, além disso sua curva de aprendizado para uso dos mesmos é fácil. O problema que vejo é apenas as peculiaridades da linguagem que torna ela traiçoeira e odiada por muitos desenvolvedores. A gambiarra nela é fácil demais.

**Comment by gabrielziegler3** [comment]
Acho uma boa alternativa, existem varios videos de implementacoes rapidas de jogos no [Coding Traing (Ex. Agar.io)](https://www.youtube.com/watch?v=JXuxYMGe4KI), pra quem quiser dar uma olhada

**Comment by arthurbdiniz** [comment]
Conforme decidido pela equipe vou fechar essa issue pelo fato de ter decidido de fazer uma plataforma digital centralizadora de projetos de software feitos pela faculdade do gama
