### ISSUE TITLE
RichPicture Geral

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/Main#13]
### Descrição
Produção do documento para documentar o projeto

### Critérios de Aceitação
- [x] Richpicture pronto.
- [x] Richpicture revisado por algum integrante do grupo

### Tarefas
- [x] Criar um diagrama no draw.io
- [x] Compartilhar na issue
- [x] Fazer um brainstorm sobre os requisitos do sistema
- [x] Modelar o richpicture em cima dos requisitos do sistema

**Comment by RomeuCarvalhoAntunes** [comment]
Coloca a imagem aqui, antes de fechar a issue.

**Comment by arthurbdiniz** [comment]
@RomeuCarvalhoAntunes 
![richpicture](https://user-images.githubusercontent.com/18387694/44621605-5a0e4e00-a87f-11e8-9a74-3a7dc20d7a08.png)

**Comment by arthurbdiniz** [comment]
Quem revisar e achar alguma coisa que esteja faltando é só comentar
@RomeuCarvalhoAntunes @victorcmoura @gabrielziegler3 @wdresende @vitorfhc @KahCosta

**Comment by arthurbdiniz** [comment]
Eu tinha conversado com o @victorcmoura e no protótipo de papel coloquei login com google e com github, talvez alguma alteração teria ser feita no fluxo da atividade de login serando em 3 ramos

**Comment by joao4018** [comment]
@arthurbdiniz Salva a imagem em jpg, em png ela abre(ampliar) com algumas falhas.
Pelo que eu entendi do projeto, para um richpicture geral, esse está muito bom, só falta mesmo as alterações que você comentou.

**Comment by arthurbdiniz** [comment]
Imagem no formato .jpg
![richpicture](https://user-images.githubusercontent.com/18387694/44638145-ab0b6880-a98b-11e8-9ebf-84b681183b70.jpg)

**Comment by arthurbdiniz** [comment]
Sobre as alterações que eu disse acho melhor a gente revisar na próxima versão do nosso richpicture para ver a necessidade do login por redes sociais ou não e assim reabrir em uma nova issue.

Como foi entregue uma versão inicial estou fechando essa issue
