### ISSUE TITLE
Subir ambiente basico de desenvolvimento e configuração

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/Main#19]
### Descrição:
Subir um projeto default django para já deixar o ambiente configurado.

### Critérios de Aceitação
- [x] Ambiente básico configurado
- [x] Instruções de como instalar e configurar no README

### Tarefas
- [x] Subir projeto no git

**Comment by gabrielziegler3** [comment]
é pra apenas subir um projeto inicial utilizando a [virtualenv](https://virtualenv.pypa.io/en/stable/)?

**Comment by vitorfhc** [comment]
@gabrielziegler3 vou subir ainda hoje o básico, sem virtualenv já que foi optado uso do docker
