### ISSUE TITLE
 Refatorar Arquivos de Issue e PR

### ISSUE THREAD

**Issue by RomeuCarvalhoAntunes** [Desenho2018-2/Main#25]
# Refatorar Arquivos de Issue e PR
---
### Descrição:
Refatorar conteúdo dos arquivos contemplando o projeto atual.

### Critérios de Aceitação
Critérios de aceitação para a Issue ser aceita.
- [ ] Documentos Refatorados.

### Tarefas
- [ ] Refatorar documento de Issue
- [ ] Refatorar documento de Pull Request

**Comment by vitorfhc** [comment]
Não entendi onde está a necessidade de refatoração, os arquivos parecem de acordo.

**Comment by RomeuCarvalhoAntunes** [comment]
Acho que me ocorreu um equívoco, pois como usei a documentação do repositório de EPS, alguns arquivos contém exemplos do Reabilitação motora, mas como é só exemplo não existe problema ....

**Comment by RomeuCarvalhoAntunes** [comment]
Issue aberta equivocadamente. Fechada !
