### ISSUE TITLE
Argumentação da Decisão do Tema

### ISSUE THREAD

**Issue by gabrielziegler3** [Desenho2018-2/Main#26]
### Criação de documento de argumentação
  - [x] Descrever o que é a argumentação. 
  - [x] Postar argumentação da decisão do tema.

**Comment by joao4018** [comment]
Postei a argumentação do tema, porém falta descrever sobre o que de fato é a argumentação.
Não achei o formato que eu coloquei bom, então ainda vai ter alteração, não o conteúdo apenas a forma que foi colocado na wiki.

**Comment by arthurbdiniz** [comment]
@joao4018 tenho uma introdução básica sobre argumentação:

# Introdução

A argumentação possui um papel essencial na sociedade. Diariamente diversas
pessoas participam de discussões, negociações, deliberações e várias outras atividades
colaborativas em que o ato de argumentar é constante. A argumentação possibilita às
pessoas ferramentas para que elas possam defender seus interesses e crenças. [(Cavalcante, A. C. A., 2014)]()

Para rastrear as argumentações feitas durante o trabalho, em relação à elicitação de requisitos,
e continuidade da rastreabilidade, foi utilizado o framework ACE 4.

O ACE 4
(JURETA; MYLOPOULOS; FAULKNER, 2009. Citado por Cavalcante, A. C. A., 2014) é um framework de argumentação
baseado em proposições que possui origem na engenharia de requisitos. Este
framework oferece maneiras de modelar e raciocinar acerca da validação relativa dos requisitos
discutidos em uma reunião.

O framework é composto de uma linguagem para representar as informações extraídas de uma discussão, uma condição
de aceitabilidade para verificar a existência de consenso entre os participantes e
procedimentos para checar a condição de aceitabilidade automaticamente.[(Cavalcante, A. C. A., 2014)]()


Os modelos de argumentação, gerados com base na linguagem contida no ACE,
são grafos direcionados com rótulos. Os vértices são classificados com base em quatro
rótulos: i, It, P e C. Os vértices com rótulo (i) representam vértices de informação que
servem de entrada ou saída para inferências (It). Os vértices com o rótulo (I) representam
a aplicação de inferências a fim de obter determinadas saídas. Os vértices com rótulo (C)
representam regras de conflito envolvendo dois ou mais vértices em um grafo. Finalmente,
os vértices com rótulo (P) representam regras de preferência envolvendo a predileção de
dois ou mais vértices do grafo. [(Cavalcante, A. C. A., 2014)]()
