### ISSUE TITLE
Fechamento Sprint 0

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/Main#30]
# Sprint do dia (20/08/2018) ao (26/08/2018)

### Presença 

| Membros           | Segunda   | Terça  | Quarta  | Quinta  | Sexta  | Sábado  | Domingo  | 
|:--------------------:|:-------------:|:--------:|:---------:|:----------:|:--------:|:--------:|:--------:|
| Arthur Diniz        | ✔️   | ✔️  | ✔️  | ✔️  | ✔️  | ❌  | ✔️ |
| Diego Resende  | ✔️   | ✔️  | ❌  | ✔️  | ✔️  | ❌  | ✔️ |
| Gabriel Ziegler   | ✔️   | ✔️  | ✔️  | ✔️  | ❌  | ✔️ | ✔️ |
| Joao Carlos        | ✔️   | ✔️  | ✔️  | ✔️  | ✔️  | ❌  | ✔️ |
| Kamila Costa      | ✔️   | ✔️  | ✔️  | ✔️  | ❌  | ❌  | ✔️ |
| Romeu Antunes  | ❌    | ❌   | ❌  | ✔️  | ❌  | ❌  | ✔️ |
| Vitor Falcão         | ✔️  | ✔️   | ✔️ | ✔️  | ❌  | ❌  | ✔️ |
| Vitor Moura         |  ✔️  | ✔️   | ✔️  | ✔️  | ❌  | ❌  | ✔️ |

# Retrospectiva 
| Bom                                        | Ruim                         | Melhorar                           | 
|:-------------------------------------:|:--------------------------:|:--------------------------------:|
|                        -                       |                  -               |                    -                     | 

> Para enviar sua retrospectiva copie o quadro vazio e substitua

**Comment by KahCosta** [comment]
| Bom                                        | Ruim                         | Melhorar                           | 
|:-------------------------------------:|:--------------------------:|:--------------------------------:|
| Definição de requisitos e projeto | Forma como a Daily foi aplicada na sprint 0|Aplicação da Daily apenas de segunda a quinta |

**Comment by wdresende** [comment]
| Bom                                        | Ruim                         | Melhorar                           | 
|:-------------------------------------:|:--------------------------:|:--------------------------------:|
| Realização da daily por issues no github    |   Daily todos os dias, acredito que não é preciso   |  Organização da daily  |

**Comment by gabrielziegler3** [comment]
| Bom | Ruim | Melhorar |
|--------|---------|-------------|
|Dailies via GH, time empenhado | Dailies em excesso |Um pouco na distribuicao de issues por membros |

**Comment by arthurbdiniz** [comment]
| Bom | Ruim | Melhorar |
|--------|---------|-------------|
| Boa interatividade do time | Maneira da aplicação da metodologia | Autonomia do time de se marcar nas issues modelagem do SCRUM para nosso contexto |
