### ISSUE TITLE
Apresentação metodologia aula dia 24/08

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/Main#4]
Materiais estão no aprender.com.br como exemplo
Aprensentação de 10 min sobre a nossa metodologia
Precisa de slides
Como vai funcionar nosso processo?
Como vamos definir isso?

* SCRUM
  * -[x] Daily Scrum
  * -[ ] Product Backlog
  * -[ ] Product Owner
  * -[x] Release Burndown
  * -[ ] Scrum Master
  * -[ ] Scrum Team
  * -[ ] Sprint Backlog
  * -[ ] Sprint Planning Meeting
  * -[ ] Sprint Retrospective
  * -[ ] Sprint Review Meeting

**Comment by arthurbdiniz** [comment]
Podemos misturar um pouco do SCRUM com XP e pesquisar sobre SAFE para ver se tem alguma coisa que podemos aplicar.

**Comment by RomeuCarvalhoAntunes** [comment]
Acho que para a apresentação é válido somente o estudo e a explicação do SCRUM. Para o projeto deverá ser avaliado as melhores técnicas de cada metodologia para ver qual a melhor forma de aplicarmos ao nosso projeto.

**Comment by KahCosta** [comment]
Acho que outros grupos vão apresentar sobre essas metodologias, não seria melhor focar no scrum e em como aplicar em nosso projeto?

**Comment by KahCosta** [comment]
Farei isso!

**Comment by arthurbdiniz** [comment]
Tentar mostar o maximo de coisas que os outros grupos ainda não tenham falado e se possível se a gente já tiver escolhido o tema mostrar:

* Qual linguagem vamos usar (Python)
* Qual motor gráfico "Engine" 
* Porque escolhemos fazer jogo (Falar sobre a facilidade de aplicação dos designs patterns
* O que já fizemos nessa primeira semana (repositório open source, template de issues, commits e branchs além de uma folha de estilo)

**Comment by arthurbdiniz** [comment]
Como estamos utilizando o github para tudo se quiserem da pra gente montar a apresentação na wiki como uma pagina, o .md permite a gente usar html também

**Comment by arthurbdiniz** [comment]
O que você acha @KahCosta ?

**Comment by KahCosta** [comment]
Eu já to montando aqui, mas você é quem sabe

**Comment by KahCosta** [comment]
Fica melhor falar primeiramente sobre o projeto escolhido e depois sobre a linguagem em que vamos desenvolver neh?

**Comment by arthurbdiniz** [comment]
Acredito que sim @KahCosta ! 
Uma boa ordem seria:

* Introdução do que vamos fazer
* Quais ferramentas vamos utilizar
* Como vamos utilizar (metodologia)

**Comment by KahCosta** [comment]
Vamos colocar em tópicos aqui os pontos da metologia Scrum que vamos aplicar!

**Comment by arthurbdiniz** [comment]
Vamos colocar na descrição dessa issue!

**Comment by arthurbdiniz** [comment]
@KahCosta os princípios fundamentais dos frameworks SCRUM, XP e SAFE estão na descrição da issue.

**Comment by joao4018** [comment]
@arthurbdiniz Talvez tenha muito conteúdo para 10 minutos, e como a @KahCosta e o @RomeuCarvalhoAntunes  comentou, nossa apresentação é sobre o SCRUM, talvez pelo tempo seria melhor apresentarmos só o SCRUM  e se cada pessoa for falar algum tópico vai ter pouco mais de 1min pra cada.

**Comment by arthurbdiniz** [comment]
@joao4018 na verdade o que quis dizer é para não perdemos tempo apresentando o SCRUM acredito que quase a sala toda vai usar e sim focar no que vamos usar das outras metodologias

**Comment by arthurbdiniz** [comment]
Apresentação ficou para a próxima segunda, sendo assim temos mais tempo para melhorar alguma coisa que estiver faltando.

**Comment by arthurbdiniz** [comment]
Vou fechar a issue pelo fato da apresentação já estar pronta e os membros da equipe sabendo o que cada um irá falar.
