### ISSUE TITLE
Daily 20/08 ⚠️

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/Main#5]
# Daily dia (20/08/2018)

### 1) Resultados do dia
Pequeno resumo dos resultados apresentados pelos membros... Issues que fooram
fechadas, documentos concluídos e ou revisados.

* O que eu fiz hoje que ajudou o Time de Desenvolvimento a atender a meta da Sprint?

### 2) Futuro da Sprint
* O que eu farei para ajudar o Time de Desenvolvimento atender a meta da Sprint?

### 3) Impedimentos identificados
Relatar pontos negativos que foram abortados durante o dia, impedimentos, dúvidas
e aflições por parte dos membros
* Eu vejo algum obstáculo que impeça a mim ou o Time de Desenvolvimento no atendimento da meta da Sprint?

### Presença

- ✔️ Arthur Diniz  
- ✔️ Diego Resende  
- ✔️ Gabriel Ziegler
- ✔️ Kamilla Costa
- ❌  Romeu Antunes
- ✔️ Victor Moura
- ✔️ Vitor Falcão
- ✔️ João Carlos

> Obs: As tarefas deverão vir comentadas nesta issue entre 22:00 e 22:15.

**Comment by vitorfhc** [comment]
1) Como sprint inicial tomei junto ao time a decisão de tema e me comprometi ao treinamento para nivelamento técnico.

2) O treinamento será elaborado e apresentado o mais breve possível. Ainda nessa sprint. Além disso um estudo de libs é frameworks que podem ser utilizados será feito.

**Comment by arthurbdiniz** [comment]
1) Abri as issues das dailys, atualizei o template de issues que o @RomeuCarvalhoAntunes fez, coloquei os integrantes do grupo no README e comecei a estudar a viabilidade de usar PyGame como engine para o projeto.

2) Elaborar a folha de estilo que e criar uma engine simples para entender como funciona a PyGame, ajudar na elaboração dos slides para a apresentação #4 

3) Nenhum impedimento identificado

**Comment by gabrielziegler3** [comment]
1. Ajudei o time na decisão de tema e comprometi para nivelamento técnico quanto a linguagem a ser utilizada (python). 
2. Ajudar na apresentação [#4](https://github.com/Desenho2018-2/Main/issues/4)
3. Nenhum.

**Comment by KahCosta** [comment]
1. Participação na tomada de decisão quanto ao tema do projeto que será desenvolvido 
2. Elaboração do slide que será utilizado na aula do dia 24/08 para auxiliar na explicação da metodologia Scrum.
3. Nenhum impedimento quanto as atividades propostas.

**Comment by wdresende** [comment]
### **1) Resultado do dia**
   Sugestão sobre possíveis projetos a ser feito na disciplina
### **2) Futuro da Sprint**
   Será organizado o projeto e ajudarei na apresentação da metodologia para a próxima aula 
### **3) Impedimentos identificados**
  Pouco conhecimento sobre o desenvolvimento de jogos, mas estudarei durante a semana.

**Comment by victorcmoura** [comment]
1. Participei da tomada de decisão sobre o tema do projeto
2. Estudos sobre adaptações de metodologias para serem usadas no projeto + estudo sobre implementações de jogos na lindefinida.guagem definida.
3. Não identifiquei impedimentos

**Comment by joao4018** [comment]
1. Participação na  decisão do tema do projeto que será desenvolvido, sugestão de ideias para a realização do projeto.
2. Participarei da apresentação da próxima aula.
3. Nenhum impedimento.

**Comment by arthurbdiniz** [comment]
Daily encerrada!

Faltas de hoje:

- @RomeuCarvalhoAntunes
