### ISSUE TITLE
Daily 22/08 🔒 

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/Main#7]
# Daily dia (22/08/2018)

### 1) Resultados do dia
Pequeno resumo dos resultados apresentados pelos membros... Issues que fooram
fechadas, documentos concluídos e ou revisados.

* O que eu fiz hoje que ajudou o Time de Desenvolvimento a atender a meta da Sprint?

### 2) Futuro da Sprint
* O que eu farei para ajudar o Time de Desenvolvimento atender a meta da Sprint?

### 3) Impedimentos identificados
Relatar pontos negativos que foram abortados durante o dia, impedimentos, dúvidas
e aflições por parte dos membros
* Eu vejo algum obstáculo que impeça a mim ou o Time de Desenvolvimento no atendimento da meta da Sprint?

### Presença

- [x] Arthur Diniz  
- [ ] Diego Resende  
- [x] Gabriel Ziegler
- [x] João Carlos
- [x] Kamilla Costa
- [ ] Romeu Antunes
- [x] Victor Moura
- [x] Vitor Falcão

> Obs: As tarefas deverão vir comentadas nesta issue entre 22:00 e 22:15.

**Comment by gabrielziegler3** [comment]
1. Ainda nao consegui ajudar no projeto hoje.
2. Irei ajudar o @joao4018 na confeccao de artefatos de pre-rastreablidade.
3. Tempo corrido.

**Comment by joao4018** [comment]
1. Revisão do slide
2. Confeccionar artefatos com o @gabrielziegler3.
3. Nenhum.

**Comment by KahCosta** [comment]
1. Não foi possivel dispor de tempo hoje para contribuição no projeto.
2. Elaboração de artefatos
3. Acumulo de entrega de atividades referente a outras disciplinas

**Comment by victorcmoura** [comment]
1. Fiquei o dia todo por conta do LAPPIS
2. Finalmente fazer algo produtivo na disciplina
3. Fiquei o dia todo por conta do LAPPIS

**Comment by vitorfhc** [comment]
1. O dia todo ocupado, inclusive até agora.
2. Focar na apresentação de sexta de uma vez.

**Comment by arthurbdiniz** [comment]
1) Fiquei o dia todo com entrega do LAPPIS
2) Focar na apresentação
3) Entrega no LAPPIS

**Comment by arthurbdiniz** [comment]
Daily encerrada!

Faltas de hoje:

@RomeuCarvalhoAntunes 
@wdresende
